version: "2"

database:
  url: ${DATABASE_URL|sqlite:auth.db?loc=auto&_fk=1}

api:
  public:
    hostname: ${API_PUBLIC_HOSTNAME|0.0.0.0}
    port: ${API_PUBLIC_PORT|8080}
  internal:
    hostname: ${API_INTERNAL_HOSTNAME|0.0.0.0}
    port: ${API_INTERNAL_PORT|1111}

admin:
  users:
    - email: ${ADMIN_USER_EMAIL|admin@example.com}
      password: ${ADMIN_USER_PASSWORD|no-secure-password}

roles:
  - name: default
    public: true

providers:
  email:
    enabled: ${PROVIDERS_EMAIL_ENABLED|true}
    jwt:
      accessSecret: ${PROVIDERS_EMAIL_JWT_ACCESS_SECRET|change-me-please}
      refreshSecret: ${PROVIDERS_EMAIL_JWT_REFRESH_SECRET|change-me-please}
      accessTokenDuration: ${PROVIDERS_EMAIL_JWT_ACCESS_TOKEN_DURATION|15m}
      refreshTokenDuration: ${PROVIDERS_EMAIL_JWT_REFRESH_TOKEN_DURATION|30d}
    webhooks:
      recoveryPasswordEvent:
        url: ${PROVIDERS_EMAIL_WEBHOOKS_RECOVERY_PASSWORD_EVENT|}
      registerEvent:
        url: ${PROVIDERS_EMAIL_WEBHOOKS_REGISTER_EVENT|}

  magiclink:
    enabled: ${PROVIDERS_MAGICLINK_ENABLED|}
    webhooks:
      loginEvent:
        url: ${PROVIDERS_MAGICLINK_WEBHOOKS_LOGIN_EVENT|}
