version: "2"

database:
  url: ${DB_URL|sqlite:auth.db?loc=auto&_fk=1}

api:
  public:
    hostname: ${AUTH_PUBLIC_HOSTNAME|0.0.0.0}
    port: ${AUTH_PUBLIC_PORT|8080}
  internal:
    hostname: ${AUTH_INTERNAL_HOSTNAME|0.0.0.0}
    port: ${AUTH_INTERNAL_PORT|1111}

admin:
  users:
    - email: ${AUTH_ADMIN_EMAIL|admin@example.com}
      password: ${AUTH_ADMIN_PASSWORD|no-secure-password}

roles:
  - name: default
    public: true

providers:
  email:
    enabled: ${PROVIDERS_EMAIL_ENABLED|true}
    jwt:
      accessSecret: ${PROVIDERS_EMAIL_JWT_ACCESS_SECRET|change-me-please}
      refreshSecret: ${PROVIDERS_EMAIL_JWT_REFRESH_SECRET|change-me-please}
    webhooks:
      recoveryPasswordEvent:
        url: ${PROVIDERS_EMAIL_WEBHOOKS_RECOVERY_PASSWORD_EVENT}
      registerEvent:
        url: ${PROVIDERS_EMAIL_WEBHOOKS_REGISTER_EVENT}

  magiclink:
    enabled: ${PROVIDERS_MAGICLINK_ENABLED}
    webhooks:
      loginEvent:
        url: ${PROVIDERS_MAGICLINK_WEBHOOKS_LOGIN_EVENT}
