db:
  url: ${DB_URL|sqlite:auth.db?loc=auto&_fk=1}

jwt:
  accessSecret: ${JWT_ACCESS_SECRET|changemeplease}
  refreshSecret: ${JWT_REFRESH_SECRET|changemeplease}

api:
  public:
    hostname: ${PUBLIC_HOSTNAME|0.0.0.0}
    port: ${PUBLIC_PORT|8080}
  internal:
    hostname: ${INTERNAL_HOSTNAME|0.0.0.0}
    port: ${INTERNAL_PORT|1111}

admin:
  users:
    - email: ${ADMIN_EMAIL|admin@example.com}
      password: ${ADMIN_PASSWORD|no-secure-password}

anonymous:
  name: public

roles:
  - name: doctor
    children:
      - patient
    users:
      - email: xxx
        password: yyy
  - name: physitian
    child: patient
  - name: patient
    public: true
    parents:
      - doctor
      - physitian

# roles:
#   - name: default
#     users:
#       - email: user1@example.com
#         password: no-secure-password
#       - email: user2@example.com
#         password: no-secure-password


<<<<<<< Updated upstream
mailersend:
  url: https://web-platform.teleus.minsky.cc/auth/recovery?token=
  key: Insert MailerSend Key Here
  template: 7dnvo4doz6g5r86y
  support: test@minsky.cc
  name: Bregy
  user:
    name: Bregy
    email: test@minsky.cc
=======
providers:
  email:
    enabled: ${PROVIDERS_EMAIL_ENABLED|true}
    jwt:
      accessSecret: ${PROVIDERS_EMAIL_JWT_ACCESS_SECRET|change-me-please}
      refreshSecret: ${PROVIDERS_EMAIL_JWT_REFRESH_SECRET|change-me-please}
      accessTokenDuration: ${PROVIDERS_EMAIL_JWT_ACCESS_TOKEN_DURATION|15m}
      refreshTokenDuration: ${PROVIDERS_EMAIL_JWT_REFRESH_TOKEN_DURATION|30d}
    webhooks:
      recoveryPasswordEvent:
        url: ${PROVIDERS_EMAIL_WEBHOOKS_RECOVERY_PASSWORD_EVENT|}
      registerEvent:
        url: ${PROVIDERS_EMAIL_WEBHOOKS_REGISTER_EVENT|}

  magiclink:
    enabled: ${PROVIDERS_MAGICLINK_ENABLED|}
    webhooks:
      loginEvent:
        url: ${PROVIDERS_MAGICLINK_WEBHOOKS_LOGIN_EVENT|}
>>>>>>> Stashed changes
