db:
  url: ${DB_URL|sqlite:auth.db?loc=auto&_fk=1}

jwt:
  accessSecret: ${JWT_ACCESS_SECRET|changemeplease}
  refreshSecret: ${JWT_REFRESH_SECRET|changemeplease}

api:
  public:
    hostname: ${PUBLIC_HOSTNAME|0.0.0.0}
    port: ${PUBLIC_PORT|8080}
  internal:
    hostname: ${INTERNAL_HOSTNAME|0.0.0.0}
    port: ${INTERNAL_PORT|1111}

admin:
  users:
    - email: ${ADMIN_EMAIL|admin@example.com}
      password: ${ADMIN_PASSWORD|no-secure-password}

anonymous:
  name: public

roles:
  - name: doctor
    children:
      - patient
    users:
      - email: xxx
        password: yyy
  - name: physitian
    child: patient
  - name: patient
    public: true
    parents:
      - doctor
      - physitian

webhooks:
  email:
    recoveryPasswordEvent:
      url: ${PROVIDERS_EMAIL_WEBHOOKS_RECOVERY_PASSWORD_EVENT}
    registerEvent:
      url: ${PROVIDERS_EMAIL_WEBHOOKS_REGISTER_EVENT}

  magiclink:
    loginEvent:
      url: ${PROVIDERS_MAGICLINK_WEBHOOKS_LOGIN_EVENT}
