db:
  url: "sqlite:auth.db?loc=auto&_fk=1"

jwt:
  accessSecret: changemeplease
  refreshSecret: changemeplease

api:
  public:
    hostname: 0.0.0.0
    port: 8080
  internal:
    hostname: 0.0.0.0
    port: 1111

admin:
  users:
    - email: admin@example.com
      password: no-secure-password

anonymous:
  name: public

roles:
  - name: default
    users:
      - email: user1@example.com
        password: no-secure-password
      - email: user2@example.com
        password: no-secure-password
      - email: bregy@minsky.cc
        password: admin1234

mailersend:
  url: https://web-platform.teleus.minsky.cc/auth/recovery?token=
  key: Insert Mailersend Key
  template: 7dnvo4doz6g5r86y
  support: test@minsky.cc
  name: Bregy
  user:
    name: Bregy
    email: test@minsky.cc
