version: "3"

tasks:
  temp-build:
    cmds:
      - go build -v -o /tmp/hasura-auth-webhook cmd/hasura-auth-webhook/*

  generate:
    cmds:
      - go run entgo.io/ent/cmd/ent generate ./ent/schema

  start:
    cmds:
      - task: temp-build
      - /tmp/hasura-auth-webhook
